### PR TITLE
Implemented action buttons for notifications

### PR DESCRIPTION
**Pull request by idoqo**
Now, pair requests can be acted upon (accepted or rejected) directly from the notification bar.

### CODE REVIEW

**Comment by albertvaka** [comment]
Sorry I haven't answered the PR before. Please note Github is just a mirror of our main git repos at cgit.kde.org, and we can't accept PRs here. I will try to test your code soon and if I don't see any issues I will push it with you as author, but the PR won't be actually merged. For future patches please use https://phabricator.kde.org/differential/diff/create/

Having a quick look at the changes, though, I have a question: Don't we need both black and white versions of the icons depending on the Android version? (Holo/Material). I remember reading something about that on the Android design guidelines, but I can't find it now.

**Comment by idoqo** [comment]
I've been trying to get a phabricator account since it appeared on the mailing list but it keeps marking my email as spam (tried gmail, outlook and a custom domain). Also, I think android auto-tint the icon depending on how it's been displayed - as long as you provides a white icon. Sorry this came late...

**Comment by albertvaka** [comment]
Was merged here: https://github.com/KDE/kdeconnect-android/commit/89ecdfc363de65a7b18cedb094e65b97b56ed0e0

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror a KDE repository. For this reason we can't accept contributions through Github. Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Pull request closed without merging**
