### PR TITLE
Updated Hungarian translation

### PR DESCRIPTION
**Pull request by BathoryPeter**

### CODE REVIEW

**Comment by albertvaka** [comment]
Hey!

Translations for KDE projects are managed by the localization teams, and unfortunately I can't accept changes via this channel (they would be overriden automatically). You will need to contact KDE's Hungarian Localization Team [1] and send the changes to them. Thanks a lot for your help!

[1] https://l10n.kde.org/team-infos.php?teamcode=hu

**Comment by BathoryPeter** [comment]
Hi Albert!
Thank you for the response. Can you tell me where can I find the the .po files of KDE Connect? 
Some days ago we held an Open Source Meetup in Budapest. I've asked there other translators about KDE Connect translation, but nobody could help me, we cannot find it on l10n.kde.org.

**Comment by albertvaka** [comment]
The .po is not in the repo, because it gets converted to and from XML automatically. It is still in the translations SVN, and you can get it from here:

https://l10n.kde.org/stats/gui/trunk-kf5/po/kdeconnect-android.po/

And the .pot are also in the SVN like other apps:

https://websvn.kde.org/trunk/l10n-support/templates/summit/messages/extragear-network/

Please let the other translators know :) Thanks for your help!

**Comment by BathoryPeter** [comment]
Magic, I spent many hours to find this!
Can I suggest to write a Translation section in the readme.md?

**Comment by albertvaka** [comment]
I don't know much about the translation process... is it actually different for kdeconnect than for other KDE  software? If it is, maybe you can submit a pull request for a readme.md with the stuff that other translators might need, as you probably know better than me :)

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror a KDE repository. For this reason we can't accept contributions through Github. Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Pull request closed without merging**
