### PR TITLE
Update README.md fixes kdeconnect-kde link

### PR DESCRIPTION
**Pull request by AndreMiras**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Thanks for your contribution :smiley:

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by albertvaka** [comment]
I'm gonna make this change to the main repo. Thanks for noticing it!

**Comment by AndreMiras** [comment]
Thank you, I saw the bot response, but I have to say, I wasn't going to update the main repo. In Github it only took me 1 minute to do it that's why I made it.

**Comment by albertvaka** [comment]
I know, it happens :sweat_smile:

**Pull request closed without merging**
